import Head from "next/head";
import Navbar from "../components/Navbar/Navbar";
import Feed from "../components/Timeline/Feed";
import Notifications from "../components/Notifications/Notifications";
import Friends from "../components/Contacts/Friends";
import News from "../components/News/News";
import AccountCard from "../components/Account/AccountCard";
import Sidebar from "../components/Navbar/Sidebar";
import { useSession, useSupabaseClient } from "@supabase/auth-helpers-react";
import Login from "./login";
import ArticleCard from "../components/ArticleCard";


export default function Home() {
  const session = useSession();
  console.log(session);

  if (!session) {
    return <Login />;
  }

  return (
    <div>
      <Head>
        <title>Social Network</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <Navbar />
        <div className="flex justify-between">
          <div className="hidden sm:flex flex-col p-4">
            <Sidebar />
          </div>
          <Feed />
          <div className="flex flex-col pt-8 sm:px-4">
            <News />
          </div>
        </div>
      </main>
    </div>
  );
}
