import Head from "next/head";
import Feed from "../components/Feed/Feed";
import { useSession } from "@supabase/auth-helpers-react";
import Login from "./login";
import LeftSidebar from "../components/Sidebar/LeftSidebar";
import RightSidebar from "../components/Sidebar/RightSidebar";
import Navbar from "../components/Navbar/Navbar";
import Footer from "../components/Footer/Footer";

export default function Home() {
  const session = useSession();

  if (!session) {
    return <Login />;
  }

  return (
    <div>
      <Head>
        <title>SocialSphere</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <Navbar />
        </div>
        <div className="flex justify-between">
          <div className="hidden w-64 bg-gray-50 md:block">
            <LeftSidebar />
          </div>
          <div className="w-full bg-gray-50">
            <Feed />
          </div>
          <div className="hidden w-64 bg-gray-50 md:block">
            <RightSidebar />
          </div>
        </div>
        <div>
          <Footer />
        </div>
      </main>
    </div>
  );
}
